version: "3.9"
services:
  db:
    image: postgres:14.3
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=todo_db
    ports:
      - "5432:5432"

